spring:
  application:
    name: service-pay
  data:
    mongodb:
      database: service-pay
      uri: mongodb://${DB_HOST}
  redis:
    database: 3
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@${CENTER_HOST}/eureka/