version: "3.3"

services:
  client:
    build: ./client/
    container_name: "client"
    depends_on:
      - server
    environment:
      API_HOST: server:8080
    ports:
      - 81:80
    restart: always
    volumes:
      - dist:/usr/src/app/dist
  server:
    build: ./server/target/docker-bin/
    container_name: "server"
    depends_on:
      - mongodb
    environment:
      DB_HOST: mongodb:27017
  mongodb:
    image: 'registry.cn-beijing.aliyuncs.com/rxjava/mongo:3.7.3-jessie'
    ports:
      - 27018:27017
    restart: always
volumes:
  dist: