version: "3.3"

services:
  client:
    build: ./client/
    container_name: "client"
    depends_on:
      - spring_server
    ports:
      - 81:80
    restart: always
  manager:
    build: ./manager/
    container_name: "manager"
    depends_on:
      - spring_server
    environment:
      API_HOST: server:8080
    ports:
      - 82:80
    restart: always
  spring_server:
    build: ./server/target/docker-bin/
    container_name: "spring_server"
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      DB_HOST: mongodb:27017
  mongodb:
    image: 'registry.cn-beijing.aliyuncs.com/rxjava/mongo:3.7.3-jessie'
    container_name: "mongodb"
    ports:
      - 27018:27017
    restart: always
