spring:
  application:
    name: service-manager
  data:
    mongodb:
      database: service-manager
      uri: mongodb://${DB_HOST}
  redis:
    database: 5
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@${CENTER_HOST}/eureka/