apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      name: rabbitmq
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: registry.cn-shanghai.aliyuncs.com/taro-mall/rabbitmq:3.7.5-management
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: admin
            - name: RABBITMQ_DEFAULT_PASS
              value: admin
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
  selector:
    matchLabels:
      app: rabbitmq
