apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: http
      port: 5671
    - name: tcp
      port: 5672
    - name: notknow
      port: 4369
    - name: admin-http
      port: 25672
    - name: admin-http2
      port: 15671
    - name: admin-tcp2
      port: 15672
  type: NodePort