apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: registry.cn-shanghai.aliyuncs.com/taro-mall/redis:4.0.4-alpine
          imagePullPolicy: IfNotPresent
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
  selector:
    matchLabels:
      app: redis
