version: "3.7"

services:
  client:
    image: "registry.cn-shanghai.aliyuncs.com/taro-mall/client:latest"
    container_name: "client-release"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.20'
          memory: 128M
    depends_on:
      - gateway-client
    ports:
      - 80:80
  gateway-client:
    #    build: ../services/rxjava-gateway/gateway-client/target/docker-bin
    image: "registry.cn-shanghai.aliyuncs.com/taro-mall/gateway-client:latest"
    container_name: "gateway-client-release"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.20'
          memory: 128M
    depends_on:
      - center
      - config
    environment:
      DB_HOST: mongodb:27017
      CENTER_HOST: center:8761
      CONFIG_HOST: config:8888
  service-goods:
    #    build: ../services/rxjava-service/service-goods/target/docker-bin
    image: "registry.cn-shanghai.aliyuncs.com/taro-mall/service-goods:latest"
    container_name: "service-goods-release"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.20'
          memory: 128M
    depends_on:
      - config
      - center
      - mongodb
      - redis
    environment:
      DB_HOST: mongodb:27017
      CENTER_HOST: center:8761
      CONFIG_HOST: config:8888
  center:
    #    build: ../services/center/target/docker-bin
    image: "registry.cn-shanghai.aliyuncs.com/taro-mall/center:latest"
    container_name: "center-release"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.20'
          memory: 128M
    depends_on:
      - config
    ports:
      - 8761:8761
    environment:
      CONFIG_HOST: config:8888
  config:
    #    build: ../services/config/target/docker-bin
    image: "registry.cn-shanghai.aliyuncs.com/taro-mall/config:latest"
    container_name: "config-release"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.20'
          memory: 128M
    restart: always
  mongodb:
    image: 'registry.cn-shanghai.aliyuncs.com/taro-mall/mongo:3.7.3-jessie'
    container_name: "mongodb-release"
    ports:
      - 27017:27017
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.20'
          memory: 128M
  redis:
    image: 'registry.cn-shanghai.aliyuncs.com/taro-mall/redis:4.0.4-alpine'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.20'
          memory: 128M
    container_name: "redis-release"