spring:
  application:
    name: service-order
  data:
    mongodb:
      database: service-order
      uri: mongodb://${DB_HOST}
  redis:
    database: 4
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@${CENTER_HOST}/eureka/