spring:
  application:
    name: service-goods
  data:
    mongodb:
      database: service-goods
      uri: mongodb://${DB_HOST}
  redis:
    database: 1
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@${CENTER_HOST}/eureka/