spring:
  application:
    name: gateway-${module.name}
  data:
    mongodb:
      uri: mongodb://common:27017
      database: gateway-${module.name}
  rabbitmq:
    host: common
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        default-requeue-rejected: true
        auto-startup: true