spring:
  application:
    name: service-user
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: service-user
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        default-requeue-rejected: true
        auto-startup: true